version : "3"
services:
  my-diary-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-diary-api
    depends_on:
      - my-diary-pg
    volumes:
      - .:/var/www/html
    restart: always
    ports:
      - "2233:80"
    environment:
      APP_NAME: 'F+L my-diary Boilerplate'
      APP_DEBUG: 'true'
      APP_URL: 'http://220.233.1.1'
      DB_CONNECTION: 'pgsql'
    networks:
      my-diary-api-network:
        ipv4_address: 220.233.1.1

  my-diary-pg:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: test_db
    container_name: my-diary-pg
    volumes:
      - my-diary-pg-disk:/var/lib/postgres
    networks:
      my-diary-api-network:
        ipv4_address: 220.233.1.2

# On-disk storage of DB data, when containers are stopped/removed
volumes:
  my-diary-pg-disk: {}

# Local network for services running using this docker-compose config
networks:
  my-diary-api-network:
    ipam:
      driver: default
      config:
        - subnet: 220.233.0.0/16
