version: 2 # CircleCI version
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/my-diary
    environment:
        - CIRCLE_PROJECT_REPONAME: my-diary

    steps:
        - run: |
            if [[ ${CIRCLE_SHELL_ENV} =~ "localbuild" ]]; then
                mkdir -p /tmp
            fi
        - checkout
        - run: docker-compose up -d
        - run: docker-compose exec my-diary-api cp .env.example .env
        - run: docker-compose exec my-diary-api composer install -n --prefer-dist
        - run: docker-compose exec my-diary-api chmod 755 -R vendor/
        - run: docker-compose exec my-diary-api chmod 777 -R storage/
        - run: docker-compose exec my-diary-api cp .env.example .env
        - run: docker-compose exec my-diary-api php artisan migrate --force
        - run: docker-compose exec my-diary-api newman run https://api.getpostman.com/collections/${POSTMAN_COLLECTION_ID}?apikey=${POSTMAN_API_KEY} -e https://api.getpostman.com/environments/${POSTMAN_ENV_ID}?apikey=${POSTMAN_API_KEY}
        - run:
            name: Heroku Staging Deploy
            command: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_UAT_APP_NAME.git HEAD:refs/heads/master
